Design and Simulation of an gene expression experiment
======================================================

# Questions
- is gene expression different in differentiated cells?
- monocytes differentiates to macrophages
- drug concentrations induce gene expression?

# Design

## 5 cases
 case | differentiated  | drug concentration  
 ------------- | ------------- | -------------  
 1 | - | 0  
 2  | + | 0  
 3 | + | 2.5  
 4 | + | 5  
 5 | + | 7  

5 genes and duplicate measurement of each sample ID

```{r packages}
library(MASS)
library(nlme)
source("../src/myFun.R")
source("../src/helpers.R")
```

```{r parameter}
mv<-c(HPRT=1000,ABCD1=900,ABCD2=10,ABCD3=700)
conc<-c(0,0,2.5,5,7)
diff<-c(0,rep(1,length(conc)-1))
hill=20
fold<-c(HPRT=1.3,ABCD1=1.3,ABCD2=5,ABCD3=5)
ec50<-c(HPRT=10,ABCD1=7,ABCD2=5,ABCD3=7)
eps<-2E-1
Sigma<-diag(rep(.1^2,length(mv)))
selGene<-c("HPRT",paste("ABCD",1:3,sep=""))
myF<-function(id,n) paste(id,n,sep="")
yy<-function(x,ymin,fa,ec50) ymin*(1+(fa-1)*plogis(hill*log(x/ec50)))
nRep<-3
nId<-length(conc)*nRep
dd<-expand.grid(Case=seq(along=conc),Rep=1:nRep,Obs=1:2,Gene=selGene)
dd$FCase<- 
  factor(myF("C", dd$Case),levels=myF("C", seq(along=conc)))
dd$ID<-paste("S",dd$Case,dd$Rep,sep="")

dd<-transform(dd,ID=factor(ID,level=paste("S",rep(seq(along=conc),each=nRep),rep(1:nRep,length(conc)),sep="")),Conc=conc[Case],mRNA=yy(conc[Case],mv[Gene],fold[Gene],ec50[Gene]))

rand<-with(dd,exp(mvrnorm(length(levels(ID)),rep(0,length(mv)),Sigma=Sigma)[ID])*mRNA)
dd$RNA<-rand
dd$obs<-exp(rnorm(nrow(dd),sd=eps))*rand 
head(dd)

```

```{r gd}
gd<-groupedData(obs~Conc|ID,dd)
plot(gd,scale=list(y=xyLogscale()),aspect="fill",outer=~Gene)
plot(gd,outer=~Gene,aspect="fill",scale=list(y=c(xyLogscale(c(1,5E4)),list(relation="free"))))

```

```{r gdF}
gd<-groupedData(obs~FCase|ID/Obs,dd)
plot(gd,displayLevel=1,collapseLevel=1,,scale=list(x=xyLogscale(c(1,1E4))),aspect="fill",inner=~Gene)

```


# lme

```{r fit1}
fms1<-lme(log10(obs)~Gene*FCase,gd,random=~1|ID)
anova(fms1)
summary(fms1)$tT
gdInt<-intervals(fms1,levels=.68)

```

# barplot


```{r barplot}
int0<-gdInt$fix
int<-int0[grep("^Gene",rownames(int0)),]
int
rownames(int)<-gsub("FCase","",gsub("Gene","",rownames(int)))
sel<-grep(":",rownames(int))
int<-int[sel,]

tmp<-unPaste(rownames(int),sep=":")
tmp
inta<-cbind(data.frame(int),Gene=tmp[[1]],FCase=tmp[[2]])
intal<-daply(inta,.(Gene),function(x){
  y<-as.matrix(x[,1:3]);
  dimnames(y)[[1]]=x$FCase
  y})
#daply(inta,.(Gene),function(x) {y<-as.matrix(x[,1:3]);y})

intal
#barPlotsInt(intal,T)
x<-intal
ym <- x[,,2];yup <-  x[,,3];ylow <-  x[,,1]
LOG=F
if(!LOG) {ym <-10^ym;yup <- 10^yup;ylow <- 10^ylow}
#LAS=2;lay=NULL;ylim=NULL;col=0
#barx <- barplot(ym,beside=T,col=col,las=LAS,ylim=ylim,ylab=ylab,legend.text=T,args.legend = list(x = leg,ncol=2,bty = "n"),layout=lay)

barx <- barplot(ym,beside=T,col=2:4,las=1,legend.text=T,args.legend = list(x = "topleft",ncol=2,bty = "n"))
abline(h=1)
error.bar(barx,ym,yup-ym,ym-ylow)

```



